# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'
gem 'bundler', '2.3.25'

# 最新のRailsを使用する場合: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.8'

# Active RecordでPostgreSQLをデータベースとして使用
gem 'pg', '~> 1.1'

# Pumaウェブサーバーを使用 [https://github.com/puma/puma]
gem 'puma', '~> 5.0'

# 画像加工
gem 'cloudinary'

# その他
gem 'rubocop', require: false, group: :development

# REXMLライブラリを追加
gem 'rexml'

# Windowsにはzoneinfoファイルが含まれないため、tzinfo-data gemをバンドル
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# キャッシュによって起動時間を短縮; config/boot.rbで必要
gem 'bootsnap', require: false

# クロスオリジンのAJAXを可能にするためにRack CORSを使用
gem 'rack-cors'

# 外部認証サービス
gem 'clerk-sdk-ruby', require: 'clerk'

# 動的なOGP画像生成のために追加
gem 'imgkit'
gem 'wkhtmltopdf-heroku', '~> 2.12.6.0'

group :development, :test do
  # デバッグ用 [https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem]
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
end

group :development do
  # 遅いマシンや大規模アプリでコマンドを高速化 [https://github.com/rails/spring]
  # gem "spring"
end
